# Generated by Django 5.1.4 on 2024-12-16 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('owner', models.CharField(choices=[('Siemens', 'Siemens')], default='Siemens', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(choices=[('Siemens', 'Siemens')], max_length=10)),
                ('address', models.GenericIPAddressField()),
                ('location', models.CharField(choices=[('Siemens', 'Siemens')], max_length=10)),
                ('dll_path', models.CharField(max_length=200)),
                ('plc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IOBrowserMapping.plc')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IOBrowserMapping.project')),
            ],
        ),
    ]
