# Generated by Django 5.1.4 on 2024-12-16 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOBrowserMapping', '0002_object'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('project', 'object')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='object',
            name='visual',
            field=models.CharField(choices=[('Conveyor', 'ConveyorVisual')], max_length=10),
        ),
    ]
